name: Publish samples project ...

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
  
      - name: Upload Binary artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: IGNF/geoportal-extensions-openlayers-samples
          ref: gh-pages
      
      - name: Download Binary artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: .
      
      - name: Build 404
        run: |
          cp index.html 404.html
  
      - name: Publish
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m "build samples"
          git push

